# -*- coding: utf-8 -*-
"""data_warehouse_DBtables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTtvqveG7j-yzogUliqAvSOgzeBPWltj
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import sqlite3

# Your shared folder path (using the shortcut)
folder_path = "/content/drive/MyDrive/Grad Project 2026"  # Adjust if name is different
print(f"Working in: {folder_path}")

# Create your database inside the shared folder
db_path = os.path.join(folder_path, "registry.db")
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

print(f"✅ Database will be created at: {db_path}")
print("✅ Ready to build the registry!")

# Create runs table
cursor.execute("""
CREATE TABLE IF NOT EXISTS runs (
    run_id INTEGER PRIMARY KEY AUTOINCREMENT,
    dataset_id TEXT NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    status TEXT CHECK(status IN ('started', 'completed', 'failed')),
    phase TEXT
);
""")

# Create datasets table
cursor.execute("""
CREATE TABLE IF NOT EXISTS datasets (
    dataset_id TEXT PRIMARY KEY,
    original_filename TEXT NOT NULL,
    source TEXT,
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    row_count INTEGER,
    column_count INTEGER,
    target_column TEXT,
    task_type TEXT CHECK(task_type IN ('classification', 'regression')),
    file_path TEXT
);
""")

# Create plans table
cursor.execute("""
CREATE TABLE IF NOT EXISTS plans (
    plan_id INTEGER PRIMARY KEY AUTOINCREMENT,
    dataset_id TEXT NOT NULL,
    plan_json TEXT NOT NULL,
    plan_yaml TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_ai_generated BOOLEAN DEFAULT 0
);
""")

# Create metrics table
cursor.execute("""
CREATE TABLE IF NOT EXISTS metrics (
    metric_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL,
    model_type TEXT,
    accuracy REAL,
    f1_score REAL,
    precision REAL,
    recall REAL,
    training_time_seconds REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
""")

conn.commit()
print("✅ All 4 tables created successfully!")

# Show what tables exist
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("\nTables in database:")
for table in tables:
    print(f"  - {table[0]}")

conn.close()

# Connect to database again
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# === INSERT FUNCTIONS (Add data) ===

def insert_run(dataset_id, status="started", phase=None):
    """Add a new pipeline run"""
    cursor.execute(
        "INSERT INTO runs (dataset_id, status, phase) VALUES (?, ?, ?)",
        (dataset_id, status, phase)
    )
    conn.commit()
    run_id = cursor.lastrowid
    print(f"✅ Run added: ID {run_id}")
    return run_id

def insert_dataset(dataset_id, filename, source, row_count, col_count, target, task_type, file_path):
    """Add dataset information"""
    cursor.execute("""
        INSERT INTO datasets
        (dataset_id, original_filename, source, row_count, column_count,
         target_column, task_type, file_path)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (dataset_id, filename, source, row_count, col_count, target, task_type, file_path))
    conn.commit()
    print(f"✅ Dataset added: {dataset_id}")

def insert_plan(dataset_id, plan_json, is_ai_generated=0):
    """Save a preprocessing plan"""
    import json
    cursor.execute("""
        INSERT INTO plans (dataset_id, plan_json, is_ai_generated)
        VALUES (?, ?, ?)
    """, (dataset_id, json.dumps(plan_json), is_ai_generated))
    conn.commit()
    plan_id = cursor.lastrowid
    print(f"✅ Plan added: ID {plan_id}")
    return plan_id

def insert_metrics(run_id, model_type, accuracy, f1_score):
    """Save model performance metrics"""
    cursor.execute("""
        INSERT INTO metrics (run_id, model_type, accuracy, f1_score)
        VALUES (?, ?, ?, ?)
    """, (run_id, model_type, accuracy, f1_score))
    conn.commit()
    print(f"✅ Metrics added for run {run_id}")

print("✅ All helper functions loaded!")

# === FETCH FUNCTIONS (Read data) ===

def get_run(run_id):
    """Fetch a specific run by ID"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM runs WHERE run_id = ?", (run_id,))
    result = cursor.fetchone()
    conn.close()
    return result

def get_runs_by_dataset(dataset_id):
    """Get all runs for a dataset"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM runs WHERE dataset_id = ? ORDER BY start_time DESC", (dataset_id,))
    result = cursor.fetchall()
    conn.close()
    return result

def get_dataset(dataset_id):
    """Fetch dataset metadata"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM datasets WHERE dataset_id = ?", (dataset_id,))
    result = cursor.fetchone()
    conn.close()
    return result

def get_all_datasets():
    """List all datasets"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT dataset_id, original_filename, row_count, task_type FROM datasets")
    result = cursor.fetchall()
    conn.close()
    return result

def get_metrics_by_run(run_id):
    """Get metrics for a specific run"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM metrics WHERE run_id = ?", (run_id,))
    result = cursor.fetchall()
    conn.close()
    return result

def get_recent_runs(limit=5):
    """Get the most recent runs (for UI dashboard)"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT r.run_id, r.dataset_id, r.start_time, r.status, r.phase,
               d.original_filename, m.accuracy, m.f1_score
        FROM runs r
        LEFT JOIN datasets d ON r.dataset_id = d.dataset_id
        LEFT JOIN metrics m ON r.run_id = m.run_id
        ORDER BY r.start_time DESC
        LIMIT ?
    """, (limit,))
    result = cursor.fetchall()
    conn.close()
    return result

# === UPDATE FUNCTIONS ===

def update_run_status(run_id, status, set_end_time=True):
    """Update run status and optionally set end time"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    if set_end_time:
        cursor.execute("""
            UPDATE runs
            SET status = ?, end_time = CURRENT_TIMESTAMP
            WHERE run_id = ?
        """, (status, run_id))
    else:
        cursor.execute("UPDATE runs SET status = ? WHERE run_id = ?", (status, run_id))
    conn.commit()
    conn.close()
    print(f"✅ Run {run_id} updated to {status}")

# === TEST FETCH AND UPDATE FUNCTIONS ===
print("\n" + "="*50)
print("TESTING FETCH AND UPDATE FUNCTIONS")
print("="*50)

# Test get_run
run = get_run(1)
print(f"\n📋 get_run(1): {run}")

# Test get_dataset
dataset = get_dataset("iris_test_v1")
print(f"📋 get_dataset('iris_test_v1'): {dataset}")

# Test get_all_datasets
all_datasets = get_all_datasets()
print(f"📋 get_all_datasets(): {all_datasets}")

# Test get_metrics_by_run
metrics = get_metrics_by_run(1)
print(f"📋 get_metrics_by_run(1): {metrics}")

# Test get_recent_runs
recent = get_recent_runs(3)
print(f"📋 get_recent_runs(3): {recent}")

# Test update_run_status
update_run_status(1, "completed", set_end_time=True)

# Verify the update worked
run_after = get_run(1)
print(f"📋 After update - get_run(1): {run_after}")

print("\n✅ All fetch and update functions tested!")

"""Note: First test with iris_test_v1 was completed successfully
and data remains in database. This test shows adding new data.
"""

# Test your functions with sample data - USE NEW ID!

# 1. Add a dataset with NEW ID
insert_dataset(
    dataset_id="iris_test_v2",  # Changed from v1 to v2
    filename="iris.csv",
    source="UCI",
    row_count=159,
    col_count=6,
    target="species",
    task_type="classification",
    file_path="data/raw_input/iris.csv"
)

# 2. Add a run
run_id = insert_run("iris_test_v2", "completed", "testing")  # Updated to v2

# 3. Add metrics for that run
insert_metrics(run_id, "random_forest", accuracy=0.95, f1_score=0.94)

# 4. Add a simple plan
sample_plan = {
    "encoder": "onehot",
    "scaler": "standard",
    "imputer": "median"
}
insert_plan("iris_test_v2", sample_plan, is_ai_generated=0)  # Updated to v2

# 5. Show what's in your tables
print("\n" + "="*40)
print("CURRENT DATA IN DATABASE:")
print("="*40)

# Reconnect since previous cell might have closed connection
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute("SELECT * FROM runs")
print("\n📋 runs table:", cursor.fetchall())

cursor.execute("SELECT dataset_id, original_filename, row_count FROM datasets")
print("\n📋 datasets table:", cursor.fetchall())

cursor.execute("SELECT * FROM metrics")
print("\n📋 metrics table:", cursor.fetchall())

conn.close()
print("\n✅ All tests passed!")

# Check the actual database file
import os

db_path = "/content/drive/MyDrive/Grad Project 2026/registry.db"

# Check if file exists
if os.path.exists(db_path):
    file_size = os.path.getsize(db_path)
    print(f"✅ Database file found!")
    print(f"📍 Location: {db_path}")
    print(f"📊 File size: {file_size} bytes")

    # List all files in your project folder
    print("\n📁 Files in your Grad Project 2026 folder:")
    project_files = os.listdir("/content/drive/MyDrive/Grad Project 2026")
    for file in project_files:
        print(f"   - {file}")
else:
    print("❌ Database file not found")
