import pandas as pd
import json
import os
import glob
from datetime import datetime


class TransformationModule:
    def __init__(self, raw_file_path, name, version):
        self.raw_file_path = raw_file_path
        self.name = name
        self.version = version
        self.df = None
        self.log = {
            "name": name,
            "version": version,
            "raw_file_path": raw_file_path,
            "steps": []
        }

    def load(self):
        self.df = pd.read_csv(self.raw_file_path)
        self.log["original_shape"] = list(self.df.shape)
        self.log["steps"].append(f"Loaded dataset: {self.df.shape[0]} rows, {self.df.shape[1]} cols")

    def remove_duplicates(self):
        before = len(self.df)
        self.df = self.df.drop_duplicates()
        removed = before - len(self.df)
        self.log["duplicates_removed"] = removed
        self.log["steps"].append(f"Removed {removed} duplicate rows")

    def fix_types(self):
        converted = []
        for col in self.df.columns:
            if self.df[col].dtype == object:
                try:
                    self.df[col] = pd.to_numeric(self.df[col], errors='raise')
                    converted.append(col)
                except (ValueError, TypeError):
                    pass
        self.log["columns_type_cast"] = converted
        self.log["steps"].append(f"Type cast attempted on: {converted}")

    def impute_missing(self):
        imputed = {}
        for col in self.df.columns:
            missing = self.df[col].isnull().sum()
            if missing > 0:
                if self.df[col].dtype in ['float64', 'int64']:
                    median_val = self.df[col].median()
                    self.df[col].fillna(median_val, inplace=True)
                    imputed[col] = {"strategy": "median", "value": median_val, "count": int(missing)}
                else:
                    mode_val = self.df[col].mode()[0]
                    self.df[col].fillna(mode_val, inplace=True)
                    imputed[col] = {"strategy": "mode", "value": str(mode_val), "count": int(missing)}
        self.log["imputed_columns"] = imputed
        self.log["steps"].append(f"Imputed missing values in {len(imputed)} columns")

    def save(self, output_dir="data/curated", log_dir="logs/transform"):
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(log_dir, exist_ok=True)

        out_path = f"{output_dir}/{self.name}_v{self.version}_cleaned.csv"
        self.df.to_csv(out_path, index=False)

        self.log["curated_path"] = out_path
        self.log["final_shape"] = list(self.df.shape)
        self.log["timestamp"] = datetime.now().isoformat()
        log_path = f"{log_dir}/{self.name}_v{self.version}_transform.json"
        with open(log_path, "w") as f:
            json.dump(self.log, f, indent=2)

        print(f"✅ {self.name}: saved to {out_path}")
        return out_path, log_path

    def transform(self):
        self.load()
        self.remove_duplicates()
        self.fix_types()
        self.impute_missing()
        return self.save()


# ── Helper: find raw file by dataset name (case‑insensitive) ──────────────

def find_raw_file(dataset_name, raw_dir="data/raw"):
    """
    Scan raw_dir for a CSV file whose filename contains dataset_name.
    Returns the relative path (from project root) or None.
    """
    if not os.path.isdir(raw_dir):
        print(f"   Warning: raw directory '{raw_dir}' does not exist.")
        return None

    # Build pattern: any file containing dataset_name (case‑insensitive)
    pattern = os.path.join(raw_dir, f"*{dataset_name}*.csv")
    matches = glob.glob(pattern)
    if not matches:
        # Try case‑insensitive fallback
        all_csv = glob.glob(os.path.join(raw_dir, "*.csv"))
        matches = [f for f in all_csv if dataset_name.lower() in os.path.basename(f).lower()]

    if matches:
        # Return the first match (or you could pick the newest with max(mtime))
        return matches[0]
    return None


# ── Runner ─────────────────────────────────────────────────────────────────

def run_transformation(summary_path="logs/validation/validation_summary.json"):
    # Load validation summary (this file is generated by T1.3)
    with open(summary_path) as f:
        summary = json.load(f)

    valid_datasets = summary["valid_datasets"]
    print(f"Found {len(valid_datasets)} valid datasets to transform.\n")

    results = []
    for dataset in valid_datasets:
        name = dataset["name"]
        version = dataset["version"]
        print(f"Processing: {name}...")

        # Find the actual raw file on disk (ignore the wrong path from JSON)
        raw_path = find_raw_file(name)
        if raw_path is None:
            print(f"❌ Could not find raw file for '{name}' in data/raw/")
            results.append({
                "name": name,
                "version": version,
                "status": "transform_failed",
                "error": "Raw file not found"
            })
            continue

        print(f"   Using raw file: {raw_path}")
        try:
            module = TransformationModule(
                raw_file_path=raw_path,
                name=name,
                version=version
            )
            curated_path, log_path = module.transform()
            results.append({
                "name": name,
                "version": version,
                "curated_path": curated_path,
                "transform_log_path": log_path,
                "status": "curated"
            })
        except Exception as e:
            print(f"❌ Failed on {name}: {e}")
            results.append({
                "name": name,
                "version": version,
                "status": "transform_failed",
                "error": str(e)
            })

    # Save a summary of what was transformed (optional)
    os.makedirs("logs/transform", exist_ok=True)
    with open("logs/transform/transform_summary.json", "w") as f:
        json.dump({"curated_datasets": [r for r in results if r["status"] == "curated"]}, f, indent=2)

    print(f"\nDone. {sum(1 for r in results if r['status'] == 'curated')}/{len(valid_datasets)} datasets transformed successfully.")


if __name__ == "__main__":
    # Ensure we are in the project root (where data/ and logs/ are)
    # If your script is inside pipelines/, this changes directory to the parent folder.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)  # go up one level from pipelines/
    os.chdir(project_root)
    print(f"Working directory set to: {os.getcwd()}\n")

    run_transformation()